Class {
	#name : 'MethodHttpRudesheim',
	#superclass : 'Object',
	#category : 'Rudesheim-HTTP-REST-REST',
	#package : 'Rudesheim-HTTP-REST',
	#tag : 'REST'
}

{ #category : 'namespace' }
MethodHttpRudesheim class >> Get [

	^ GetMethodHttpRudesheim.
]

{ #category : 'namespace' }
MethodHttpRudesheim class >> Patch [

	^ PatchMethodHttpRudesheim
]

{ #category : 'namespace' }
MethodHttpRudesheim class >> Post [

	^ PostMethodHttpRudesheim.
]
